name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
     
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o WebAPI_template
    
    - name: local remote scp
      uses: cross-the-world/scp-pipeline@master
      with:
        host: ${{ secrets.ServerHost }}
        user: ${{ secrets.ServerUsername }}
        pass: ${{ secrets.ServerPassword }}
        local: "bin/Release/netcoreapp3.1/WebAPI_template.dll"
        remote: c:\inetpub3\
    
