name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o WebAPI_template
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        #version: "320.0.1"
        service_account_key: ${{ secrets.gcp_api_temp_dev_credentials }}
        project_id: ${{ secrets.gcp_api_temp_dev_project_id }}
        export_default_credentials: true
    
    #- run: gcloud auth list
    #- run: gcloud config set account 15400162913-compute@developer.gserviceaccount.com
    #- run: gcloud config set account `ACCOUNT`
    
    #- name: List out directory contents
    #  run: |
    #      echo "Listing the contents of the GitHub workspace directory"
    #      ls ${{ github.workspace }}
    #      echo "Recursively listing all contents of the current directory"
    #      ls -R
      
    - name: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        project_id: ${{ secrets.gcp_api_temp_dev_project_id }}
        #deliverables: https://raw.githubusercontent.com/tangungithub/API_Test_Automated/main/.github/workflows/app.yml
        deliverables: ./app.yml
        credentials: ${{ secrets.gcp_api_temp_dev_credentials }}
    # Example of using the output
    - name: test
      run: curl "${{ steps.deploy.outputs.url }}"
