name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: "290.0.1"
        service_account_key: ${{ secrets.gcp_api_temp_dev_credentials }}
        project_id: ${{ secrets.gcp_api_temp_dev_project_id }}
    
    - name: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        project_id: ${{ secrets.gcp_api_temp_dev_project_id }}
        credentials: ${{ secrets.gcp_api_temp_dev_credentials }}
    # Example of using the output
    - name: test
      run: curl "${{ steps.deploy.outputs.url }}"
